name: Auto Commit and Update

on:
  schedule:
    - cron: "0 */2 * * *" # Runs every 2 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create an empty commit
      run: |
        git commit --allow-empty -m "Automated empty commit to trigger update"

    - name: Push changes
      run: |
        git push origin main

    - name: Sleep for a few seconds (optional)
      run: |
        sleep 10
