name: Auto Commit and Update

on:
  schedule:
    - cron: "0 */2 * * *" # Runs every 2 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch AI contributors
      run: |
        echo "Fetching AI-related contributors..."
        contributors=(
          "openai"
          "cohere-ai"
          "Anthropic"
          "karpathy"
          "fastai"
          "GoogleResearch"
          "huggingface"
        )
        echo "# Contributors" > CONTRIBUTORS.md
        for contributor in "${contributors[@]}"; do
          echo "- $contributor" >> CONTRIBUTORS.md
        done

    - name: Commit updated contributors list
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add CONTRIBUTORS.md
          git commit -m "Update CONTRIBUTORS.md with popular AI-related contributors"
        else
          echo "No changes to commit."
        fi

    - name: Push changes
      run: |
        git push origin main

    - name: Sleep for a few seconds (optional)
      run: |
        sleep 10
